import type { DataSource } from "./MasonryDynamic";

export const mockPlaylists: DataSource[] = [
  {
    id: "1",
    name: "Post",
    color: "#3b82f6",
    items: [
      {
        imgLink: "https://picsum.photos/200",
        size: "SQUARE",
        songName: "Song A",
        artistName: "Artist 1",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/201",
        size: "SQUARE",
        songName: "Song B",
        artistName: "Artist 2",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/202",
        size: "PORTRAIT",
        songName: "Song C",
        artistName: "Artist 3",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/203",
        size: "SQUARE",
        songName: "Song D",
        artistName: "Artist 4",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/204",
        size: "PORTRAIT",
        songName: "Song E",
        artistName: "Artist 5",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/205",
        size: "SQUARE",
        songName: "Song F",
        artistName: "Artist 6",
        userID: "",
        songID: "",
      },
    ],
  },
  {
    id: "2",
    name: "Likes",
    color: "#ef4444",
    items: [
      {
        imgLink: "https://picsum.photos/206",
        size: "PORTRAIT",
        songName: "Song G",
        artistName: "Artist 7",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/207",
        size: "SQUARE",
        songName: "Song H",
        artistName: "Artist 8",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/208",
        size: "PORTRAIT",
        songName: "Song I",
        artistName: "Artist 9",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/209",
        size: "SQUARE",
        songName: "Song J",
        artistName: "Artist 10",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/210",
        size: "PORTRAIT",
        songName: "Song K",
        artistName: "Artist 11",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/211",
        size: "SQUARE",
        songName: "Song L",
        artistName: "Artist 12",
        userID: "",
        songID: "",
      },
    ],
  },
  {
    id: "3",
    name: "Workout Hits",
    color: "#10b981",
    items: [
      {
        imgLink: "https://picsum.photos/212",
        size: "SQUARE",
        songName: "Song M",
        artistName: "Artist 13",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/213",
        size: "SQUARE",
        songName: "Song N",
        artistName: "Artist 14",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/214",
        size: "PORTRAIT",
        songName: "Song O",
        artistName: "Artist 15",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/215",
        size: "SQUARE",
        songName: "Song P",
        artistName: "Artist 16",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/216",
        size: "PORTRAIT",
        songName: "Song Q",
        artistName: "Artist 17",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/217",
        size: "SQUARE",
        songName: "Song R",
        artistName: "Artist 18",
        userID: "",
        songID: "",
      },
    ],
  },
  {
    id: "4",
    name: "Party Mix",
    color: "#f59e0b",
    items: [
      {
        imgLink: "https://picsum.photos/218",
        size: "PORTRAIT",
        songName: "Song S",
        artistName: "Artist 19",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/219",
        size: "SQUARE",
        songName: "Song T",
        artistName: "Artist 20",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/220",
        size: "PORTRAIT",
        songName: "Song U",
        artistName: "Artist 21",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/221",
        size: "SQUARE",
        songName: "Song V",
        artistName: "Artist 22",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/222",
        size: "PORTRAIT",
        songName: "Song W",
        artistName: "Artist 23",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/223",
        size: "SQUARE",
        songName: "Song X",
        artistName: "Artist 24",
        userID: "",
        songID: "",
      },
    ],
  },
  {
    id: "5",
    name: "Evening Jazz",
    color: "#8b5cf6",
    items: [
      {
        imgLink: "https://picsum.photos/224",
        size: "SQUARE",
        songName: "Song Y",
        artistName: "Artist 25",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/225",
        size: "SQUARE",
        songName: "Song Z",
        artistName: "Artist 26",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/226",
        size: "PORTRAIT",
        songName: "Song AA",
        artistName: "Artist 27",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/227",
        size: "SQUARE",
        songName: "Song AB",
        artistName: "Artist 28",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/228",
        size: "PORTRAIT",
        songName: "Song AC",
        artistName: "Artist 29",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/229",
        size: "SQUARE",
        songName: "Song AD",
        artistName: "Artist 30",
        userID: "",
        songID: "",
      },
    ],
  },
  {
    id: "6",
    name: "Road Trip",
    color: "#ec4899",
    items: [
      {
        imgLink: "https://picsum.photos/230",
        size: "PORTRAIT",
        songName: "Song AE",
        artistName: "Artist 31",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/231",
        size: "SQUARE",
        songName: "Song AF",
        artistName: "Artist 32",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/232",
        size: "PORTRAIT",
        songName: "Song AG",
        artistName: "Artist 33",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/233",
        size: "SQUARE",
        songName: "Song AH",
        artistName: "Artist 34",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/234",
        size: "PORTRAIT",
        songName: "Song AI",
        artistName: "Artist 35",
        userID: "",
        songID: "",
      },
      {
        imgLink: "https://picsum.photos/235",
        size: "SQUARE",
        songName: "Song AJ",
        artistName: "Artist 36",
        userID: "",
        songID: "",
      },
    ],
  },
];
